### ISSUE TITLE
ofxGAkit vs. ofxGAKit

### ISSUE THREAD

**Issue by shi-weili** [gallagher-tech/ofxGAkit#3]
The `addons.make` in the example folders refers to the addon as `ofxGAKit`, while the addon itself declares it as `ofxGAkit` in `addon_config.mk`.

This probably doesn't cause any issue in Windows, but in macOS, it prevents projectGenerator from finding the addon.

**Comment by peterobbin** [comment]
I will make the change and make sure the name is consistent.

**Comment by tyhenry** [comment]
I just fixed this in PR #5
