### ISSUE TITLE
Building errors in macOS

### ISSUE THREAD

**Issue by shi-weili** [gallagher-tech/ofxGAkit#4]
I'm trying to get the `example-basic` running in macOS 13.2.1 on an Apple Silicon computer.

The openFrameworks version I use is `of_v0.11.2_osx_release`. I've verified that it's working by building and running `3DPrimitivesExample`.

My progress so far:

* In `addons.make`, change `ofxGAKit` to `ofxGAkit`.
* Use `projectGenerator` to generate Xcode project files.
* **Problem:** sigslot actually uses C++14 instead of C++11.
* Enable C++14 support and build
    * For both the project and the target, in `Build Settings` - `All` - `Apple Clang - Language - C++` - `C++ Language Support`, select `C++ 14 [-std=c++14]`.
* To fix the`Extra qualification on member 'xxx'` errors,
    * In `scene.h`, remove `Scene::` before `getNodes()`.
    * In `paragraph_component.h` , remove `Paragraph::` before `parseMarkdownStyles`.
* Then in `macOS 13.1/usr/include/c++/v1/__locale`, I got multiple errors:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__locale:254:54 Implicit instantiation of undefined template 'std::ctype<unsigned char>'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__locale:893:12 No matching function for call to 'use_facet'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__locale:901:44 Implicit instantiation of undefined template 'std::ctype<unsigned char>'
```

I got stuck there.

Another direction might be retrofit sigslot to C++11, but that doesn't look straightforward as well.

I also attempted to build ofxGAkit with the master branch of openFrameworks from GitHub, but getting oF itself properly configured wasn't as straightforward as I expected. I wasn't able to get projectGenerator properly built. I was able to use the PG from oF v0.11.2 to generate project files for oF examples, and build and run `3DPrimitivesExample`. But PG couldn't properly generate project files for `example-basic`.

**Comment by tyhenry** [comment]
Should be fixed in GAkit PR https://github.com/gallagher-tech/GAkit/pull/3
